logging:
  file: log/gazpar2mqtt.log
  console: true  
  level: debug
  format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'

${GRDF_CONFIG}

${MQTT_CONFIG}

homeassistant:
  discovery: true
  discovery_topic: homeassistant
  devices:    
  - device_name: gazpar
    device_unique_id: "0x52e31847e180405"
    payloads:
      card: 
        object_id: gazpar_card
        device_class: energy
        enabled_by_default: true
        icon: mdi:fire
        state_class: total_increasing
        state_topic: gazpar2mqtt/gazpar
        unit_of_measurement: kWh
        json_attributes_topic: gazpar2mqtt/gazpar
        value_template: "{{ value_json.energy }}"

      energy: 
        object_id: gazpar_energy
        device_class: energy
        enabled_by_default: true
        icon: mdi:fire
        state_class: total_increasing
        state_topic: gazpar2mqtt/gazpar
        unit_of_measurement: kWh
        value_template: "{{ value_json.energy }}"

      volume: 
        object_id: gazpar_volume
        device_class: gas
        enabled_by_default: true
        icon: mdi:fire
        state_class: total_increasing
        state_topic: gazpar2mqtt/gazpar
        unit_of_measurement: "m³"
        value_template: "{{ value_json.volume }}"
      
      temperature: 
        object_id: gazpar_temperature
        device_class: temperature
        enabled_by_default: true
        icon: mdi:thermometer
        state_class: measurement
        state_topic: gazpar2mqtt/gazpar
        unit_of_measurement: "°C"
        value_template: "{{ value_json.temperature }}"
