grdf.username: ${GRDF_USERNAME}
grdf.password: ${GRDF_PASSWORD}
grdf.pce_identifier: ${GRDF_PCE_IDENTIFIER}

homeassistant.host: ${HOMEASSISTANT_HOST}
homeassistant.port: ${HOMEASSISTANT_PORT}
homeassistant.token: ${HOMEASSISTANT_TOKEN}
