services:
  gazpar2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssenart/gazpar2mqtt:latest
    container_name: gazpar2mqtt
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./docker/config:/app/config
      - ./docker/log:/app/log
    environment:
      - GRDF_USERNAME=
      - GRDF_PASSWORD=
      - GRDF_PCE_IDENTIFIER=
      - MQTT_BROKER=
      - UID=1000
      - GID=1000
