---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
  armhf: ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20
  i386: ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Gazpar2MQTT add-on"
  org.opencontainers.image.description: "Gateway that reads data history from the GrDF (French gas provider) meter and send it to a MQTT message broker."
  org.opencontainers.image.source: "https://github.com/ssenart/gazpar2mqtt"
  org.opencontainers.image.licenses: "MIT"
args:
  GAZPAR2MQTT_VERSION: "0.2.0"