## Documentation: https://docs.docker.com/build/ci/github-actions/multi-platform/

name: "publish-to-dockerhub"
description: "Publish to DockerHub workflow"

inputs:
  image:
    description: "Docker image name"
    required: true
  version:
    description: "Version of the image"
    required: true
  is_latest: 
    description: "Whether the version is a final release"
    required: false
    default: false
  username:
    description: "DockerHub username"
    required: true
  password:
    description: "DockerHub password"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          } 

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          # Set the version tag for all branches
          type=raw,value=${{ inputs.version }}
          # Set latest tag for the default branch
          type=raw,value=latest,enable=${{ inputs.is_latest }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        file: ./docker/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
