name: Publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish, an existing tag (e.g. 0.5.1a4)"
        required: true
        type: string
      is_latest:
        description: "Update the 'latest' tag (final versions only)"
        required: false
        default: false
        type: boolean

permissions:
  contents: read # Readonly permissions

jobs:
  #----------------------------------------------
  # Publish Docker image to DockerHub
  publish-to-dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      #----------------------------------------------
      #  Check-out the tag from the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      #----------------------------------------------
      # Publish the Docker image
      - name: Publish Docker image
        uses: ./.github/workflows/publish-to-dockerhub
        with:
          image: ssenart/gazpar2mqtt
          version: ${{ inputs.version }}
          is_latest: ${{ inputs.is_latest }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
